### ISSUE TITLE
More robust handling of broken entrypoints

### ISSUE THREAD

**Issue by betatim** [jupyterhub/jupyter-server-proxy#107]
Can we/should we make jupyter server proxy more robust against broken entrypoints? I just had the case where I forgot to import a module in my package that has an entrypoint for server proxy and as a result none of the jupyter server proxy worked.

```
[W 13:54:48.009 NotebookApp] Error loading server extension jupyter_server_proxy
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.7/site-packages/notebook/notebookapp.py", line 1575, in init_server_extensions
        func(self)
      File "/srv/conda/lib/python3.7/site-packages/jupyter_server_proxy/__init__.py", line 27, in load_jupyter_server_extension
        server_proccesses += get_entrypoint_server_processes()
      File "/srv/conda/lib/python3.7/site-packages/jupyter_server_proxy/config.py", line 68, in get_entrypoint_server_processes
        make_server_process(entry_point.name, entry_point.load()())
      File "/home/thead/jupyter_vscode_proxy/__init__.py", line 21, in setup_vscode
        'icon_path': os.path.join(os.path.dirname(os.path.abspath(__file__)), 'icons', 'vscode.svg')
    NameError: name 'os' is not defined
```

**Comment by manics** [comment]
Advantage: everything else just works
Disadvantage: if you've got multiple apps you need to test them all

Could this optionally be done at the notebook level, so a failure in any extension prevents the notebook starting up?

**Comment by yuvipanda** [comment]
Yeah, I'd really like this to happen at the notebook level - so we can 'fail fast'. Should only happen for python failues like this though, not for failure of process itself to start.
