### ISSUE TITLE
Issue with websocket connection when updating from 1.5.3 to 1.6.0

### ISSUE THREAD

**Issue by bloussou** [jupyterhub/jupyter-server-proxy#261]
### Bug description
I'm using an extension that is trying to connect through websockets to a server which is in docker. After updating to version 1.6.0 it fails to connect.

### Your personal set up
This appears after updating from  1.5.3 to 1.6.0.

 - OS:
ubuntu 20.04
 - Version(s):
python 3.8.5

- <details><summary>Full environment</summary>

```
aiohttp==3.7.3
alabaster==0.7.12
anyio==2.0.2
apipkg==1.5
appdirs==1.4.4
argon2-cffi==20.1.0
astroid==2.4.2
async-generator==1.10
async-timeout==3.0.1
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
bandit==1.7.0
beautifulsoup4==4.9.3
black==20.8b1
blackdoc==0.3.1
bleach==3.2.1
cachetools==4.2.0
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
click==7.1.2
colorama==0.4.4
cryptography==3.3.1
cssselect==1.1.0
cssutils==1.0.2
decorator==4.4.2
deepdiff==5.0.2
defusedxml==0.6.0
docutils==0.16
entrypoints==0.3
execnet==1.7.1
gitdb==4.0.5
GitPython==3.1.11
idna==2.10
imagesize==1.2.0
iniconfig==1.1.1
ipykernel==5.4.2
ipython==7.19.0
ipython-genutils==0.2.0
isort==5.6.4
jdk4py==11.0.9.0
jedi==0.17.2
jeepney==0.6.0
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-core==4.7.0
jupyter-server==1.2.1
jupyter-server-proxy==1.6.0
jupyterlab==3.0.8
jupyterlab-pygments==0.1.2
jupyterlab-server==2.1.1
keyring==21.5.0
lazy-object-proxy==1.4.3
lxml==4.6.2
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.6.0
multidict==5.1.0
mypy-extensions==0.4.3
nbclassic==0.2.5
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nbsphinx==0.8.0
nest-asyncio==1.4.3
notebook==6.1.5
numpy==1.19.3
ordered-set==4.0.2
packaging==20.8
pandas==1.1.4
pandocfilters==1.4.3
parso==0.7.1
pathspec==0.8.1
pbr==5.5.1
pexpect==4.8.0
pickleshare==0.7.5
pip==21.0.1
pkginfo==1.6.1
pluggy==0.13.1
premailer==3.7.0
prometheus-client==0.9.0
prompt-toolkit==3.0.8
ptyprocess==0.6.0
py==1.10.0
py4j==0.10.9
pyarrow==2.0.0
pycparser==2.20
pydocstyle==5.1.1
Pygments==2.7.3
PyJWT==2.0.0
pylint==2.6.0
pyparsing==2.4.7
pyrsistent==0.17.3
pyspark==3.0.1
pytest==6.2.1
pytest-forked==1.3.0
pytest-tornasync==0.6.0.post2
pytest-xdist==2.2.0
python-dateutil==2.8.1
pytz==2020.4
PyYAML==5.3.1
pyzmq==20.0.0
readme-renderer==28.0
regex==2020.11.13
requests==2.25.1
requests-toolbelt==0.9.1
rfc3986==1.4.0
scipy==1.5.4
SecretStorage==3.3.0
Send2Trash==1.5.0
setuptools==52.0.0
simpervisor==0.4
six==1.15.0
smmap==3.0.4
sniffio==1.2.0
snowballstemmer==2.0.0
soupsieve==2.1
Sphinx==3.4.3
sphinx-autodoc-typehints==1.11.1
sphinx-copybutton==0.3.1
sphinx-rtd-theme==0.5.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
stevedore==3.3.0
terminado==0.9.1
testpath==0.4.4
toml==0.10.2
tornado==6.1
tqdm==4.54.1
traitlets==5.0.5
twine==3.2.0
typed-ast==1.4.1
typeguard==2.10.0
typing-extensions==3.7.4.3
urllib3==1.26.2
wcwidth==0.2.5
webencodings==0.5.1
wheel==0.36.2
wrapt==1.12.1
yarl==1.6.3
```
</details>

- <details><summary>Logs</summary>

```
[I 2021-03-25 17:06:46.073 ServerApp] Trying to establish websocket connection to ws://localhost:8081/pivot/pivot/ws/v4
[E 2021-03-25 17:06:46.082 ServerApp] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fb8e51119d0>>, <Task finished name='Task-230' coro=<ProxyHandler.proxy_open.<locals>.start_websocket_connection() done, defined at /home/brieuc/.cache/pypoetry/virtualenvs/atoti-root-Bdsr3T0L-py3.8/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py:312> exception=HTTP 401: Unauthorized>)
    Traceback (most recent call last):
      File "/home/brieuc/.cache/pypoetry/virtualenvs/atoti-root-Bdsr3T0L-py3.8/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
        ret = callback()
      File "/home/brieuc/.cache/pypoetry/virtualenvs/atoti-root-Bdsr3T0L-py3.8/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
        future.result()
      File "/home/brieuc/.cache/pypoetry/virtualenvs/atoti-root-Bdsr3T0L-py3.8/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 316, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized
```
</details>

**Comment by manics** [comment]
Hi! Would you mind trying the latest release `3.0.2`? Could you also try turning on debug logging in Jupyter and show us the full set of logs, including from before the error in case there's a problem with some setup?

Is there an easy way we can reproduce your bug from scratch, e.g. a self-contained Docker image we could run?

**Comment by bloussou** [comment]
Hello,
I've found my mistake. From `1.5.2` to `1.6.0+` the command I used to disable `jupyter_server_proxy` changed from `jupyter serverextension disable jupyter_server_proxy` to `jupyter server extension disable jupyter_server_proxy`
