### ISSUE TITLE
DistributionNotFound(Requirement.parse('webcolors>=1.11; extra == "format-nongpl"'),

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/jupyter-server-proxy#378]
### Bug description

I have a brand new, custom JupyterLab (Ubuntu 22.04) container with an analytics stack installed via `micromamba`/`conda-forge`. When I start JupyterLab in my container I observe the error in the title:
```
<snip>
[I 2023-03-03 22:21:57.075 FileIdExtension] Attached event listeners.
[I 2023-03-03 22:21:57.075 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-03-03 22:21:57.076 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[W 2023-03-03 22:21:57.420 ServerApp] jupyter_server_proxy | extension failed loading with message: DistributionNotFound(Requirement.parse('webcolors>=1.11; extra == "format-nongpl"'), {'jsonschema'})
    Traceback (most recent call last):
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 356, in load_extension
        extension.load_all_points(self.serverapp)
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 228, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 228, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 219, in load_point
        return point.load(serverapp)
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 147, in load
        return loader(serverapp)
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/jupyter_server_proxy/__init__.py", line 30, in _load_jupyter_server_extension
        server_processes += get_entrypoint_server_processes(serverproxy_config)
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/jupyter_server_proxy/config.py", line 83, in get_entrypoint_server_processes
        server_process_config = entry_point.load()()
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2470, in load
        self.require(*args, **kwargs)
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2493, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/opt/mambaforge/envs/quantdev/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'webcolors>=1.11; extra == "format-nongpl"' distribution was not found and is required by jsonschema
[I 2023-03-03 22:21:57.423 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-03-03 22:21:57.423 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
<snip>
```
<br>

> **Note**
> This doesn't stop JupyterLab from otherwise appearing to load/run fine

The message is correct - I have `jsonschema` installed but not `webcolors`:
```
❯ micromamba list | rg '(jupyterlab|jupyter-server-proxy|jsonschema|webcolors)'
  jsonschema                     4.17.3        pyhd8ed1ab_0             conda-forge
  jupyter-server-proxy           3.2.2         pyhd8ed1ab_0             conda-forge
  jupyterlab                     3.6.1         pyhd8ed1ab_0             conda-forge
  <snip>
  python-fastjsonschema          2.16.3        pyhd8ed1ab_0             conda-forge
```
```
❯ micromamba list webcolors
List of packages in environment: "/opt/mambaforge/envs/quantdev"

```

I suspected a `conda-forge` packaging error (missing the `webcolors` dep) but when I looked at the `jsonschema` package, `webcolors` is clearly an ***optional*** dependency:
https://github.com/python-jsonschema/jsonschema/blob/v4.17.3/pyproject.toml#L45-L65

...so, I've no idea why the `juypyter_server_proxy` extension is failing to load??

**Comment by takluyver** [comment]
What version of `setuptools` do you have installed, and is it possible to upgrade it? I wonder if this could be a bug in pkg_resources (which is part of setuptools).

**Comment by dhirschfeld** [comment]
Sorry, been a bit hectic. `setuptools` is 65.6.3

![image](https://user-images.githubusercontent.com/881019/223976392-5abfd037-7d77-47c3-86ed-1fa71fa7c575.png)

**Comment by Finesim97** [comment]
Hi, I am having the same issue with `67.6.1` while using mamba on the Spark Docker Jupyter stack.

**Comment by Finesim97** [comment]
With `pkg_resources` being deprecated, the switch to `importlib.metadata` might be the right move here, even though maybe it still should be fixed in there, as people are still using it, but I am not sure how the politics work regarding something like that. 

I will create a PR replacing `pkg_resources`.

**Comment by Finesim97** [comment]
Forgot the most important part, I have the rstudio and vscode proxies installed and this error message comes when loading the rstudio proxy entry point.

**Comment by Finesim97** [comment]
The bug is also only reproducible when using conda/mamba.

The old code runs fine when using pip+venv (3.10):

```sh
python -m venv setuptoolsbug
source setuptoolsbug/bin/activate
pip install setuptools jupyter-rsession-proxy
# Now copy and paste the old and new code for testing
python
```

However, when using conda, only the importlib.metadata version works:

```sh 
mamba create -p setuptoolsbugconda python=3.10
conda activate setuptoolsbugconda
mamba install jupyter-rsession-proxy
# Now copy and paste the old and new code for testing
python
```


Old code, explodes:

```
import pkg_resources

for entry_point in pkg_resources.iter_entry_points('jupyter_serverproxy_servers'):
    name = entry_point.name
    print(name)
    server_process_config = entry_point.load()()
    print(server_process_config)
```

New code, might explode behind closed doors:

```
from importlib.metadata import entry_points

for entry_point in entry_points().select(group='jupyter_serverproxy_servers'):
    name = entry_point.name
    print(name)
    server_process_config = entry_point.load()()
    print(server_process_config)
```
